name: Directus Extension

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  call-workflow:
    uses: wellenplan/actions/.github/workflows/directus-extension.yaml@v0.2.0
    with:
      # TODO: remove once repo is ready
      publish: false
    secrets:
      ORGA_USER_TOKEN: ${{ secrets.ORGA_USER_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
